# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptc_api_back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalities', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('visas', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('visited_countries', models.CharField(max_length=255)),
                ('vaccines', models.CharField(max_length=255)),
                ('residence_country', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelerProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='user',
        ),
        migrations.AlterField(
            model_name='trip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
    ]
