# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0002_auto_20171123_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='traveler',
            new_name='user',
        ),
    ]
