# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0004_auto_20171123_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerprofile',
            name='traveler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travelerProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
