# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0006_auto_20171123_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerprofile',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
