# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0009_auto_20171123_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelerProfile',
            new_name='Profile',
        ),
    ]
