# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptc_api_back', '0010_auto_20171123_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='traveler',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
