# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0012_task_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='task',
            name='traveler',
        ),
    ]
