# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptc_api_back', '0013_auto_20171124_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
