# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='ZZ', max_length=2),
            preserve_default=False,
        ),
    ]
